In [1]:
import numpy as np 
import pandas as pd 
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        path=os.path.join(dirname, filename)

/kaggle/input/gender-classification-dataset/gender_classification_v7.csv


Every human face is different and has its own features of various lengths which define if a person is male or female. We have used the gender recognition dataset from Kaggle which consists of 5000 rows and 8 columns. The final column represents the gender of the person which is our class label, and the remaining 7 features describe lengths of various features of the human face. The following is the description of each column.

a Long_hair: if the hair is short  its is labelled as 0 and 1 if the hair is long


b.	Forehead width cm: the width of forehead of a face in cms

c.	Forehead height cm: the height of forehead of a face in cms

d.	Nose width: if the nose is wide  then its labelled as 1 and 0 if the nose is not wide

e.	Nose long: if the nose is long  then  its labelled as 1 and 0 if the nose is not long

f.	Lip thin: if the lips are thin then   its labelled as 1 and 0 if the lips are not thin

g.	Distance_nose_to_lip_long: if the distance between nose and lips is long  its  labelled as 1 and 0 if its short.

h.	Gender: gender of a person


In [2]:
gender_data=pd.read_csv(path)
gender_data

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0             1               11.8                 6.1          1          0   
1             0               14.0                 5.4          0          0   
2             0               11.8                 6.3          1          1   
3             0               14.4                 6.1          0          1   
4             1               13.5                 5.9          0          0   
...         ...                ...                 ...        ...        ...   
4996          1               13.6                 5.1          0          0   
4997          1               11.9                 5.4          0          0   
4998          1               12.9                 5.7          0          0   
4999          1               13.2                 6.2          0          0   
5000          1               15.4                 5.4          1          1   

      lips_thin  distance_nose_to_lip_long  gender  
0             1                          1    Male  
1             1                          0  Female  
2             1                          1    Male  
3             1                          1    Male  
4             0                          0  Female  
...         ...                        ...     ...  
4996          0                          0  Female  
4997          0                          0  Female  
4998          0                          0  Female  
4999          0                          0  Female  
5000          1                          1    Male  

[5001 rows x 8 columns]

In [3]:
gender_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   long_hair                  5001 non-null   int64  
 1   forehead_width_cm          5001 non-null   float64
 2   forehead_height_cm         5001 non-null   float64
 3   nose_wide                  5001 non-null   int64  
 4   nose_long                  5001 non-null   int64  
 5   lips_thin                  5001 non-null   int64  
 6   distance_nose_to_lip_long  5001 non-null   int64  
 7   gender                     5001 non-null   object 
dtypes: float64(2), int64(5), object(1)
memory usage: 312.7+ KB


In [4]:
#4.	To have the statistical inference we will be using the describe() function which gives us the count, mean, standard deviation, maximum and minimum values and also the quartiles of the data.
gender_data.describe()

long_hair  forehead_width_cm  forehead_height_cm    nose_wide  \
count  5001.000000        5001.000000         5001.000000  5001.000000   
mean      0.869626          13.181484            5.946311     0.493901   
std       0.336748           1.107128            0.541268     0.500013   
min       0.000000          11.400000            5.100000     0.000000   
25%       1.000000          12.200000            5.500000     0.000000   
50%       1.000000          13.100000            5.900000     0.000000   
75%       1.000000          14.000000            6.400000     1.000000   
max       1.000000          15.500000            7.100000     1.000000   

         nose_long    lips_thin  distance_nose_to_lip_long  
count  5001.000000  5001.000000                5001.000000  
mean      0.507898     0.493101                   0.498900  
std       0.499988     0.500002                   0.500049  
min       0.000000     0.000000                   0.000000  
25%       0.000000     0.000000                   0.000000  
50%       1.000000     0.000000                   0.000000  
75%       1.000000     1.000000                   1.000000  
max       1.000000     1.000000                   1.000000

In [5]:
gender_data['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [6]:
gender_data["gender"]=gender_data["gender"].replace({"Male":0,"Female":1})

In [7]:
gender_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   long_hair                  5001 non-null   int64  
 1   forehead_width_cm          5001 non-null   float64
 2   forehead_height_cm         5001 non-null   float64
 3   nose_wide                  5001 non-null   int64  
 4   nose_long                  5001 non-null   int64  
 5   lips_thin                  5001 non-null   int64  
 6   distance_nose_to_lip_long  5001 non-null   int64  
 7   gender                     5001 non-null   int64  
dtypes: float64(2), int64(6)
memory usage: 312.7 KB


In [8]:
gender_data

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0             1               11.8                 6.1          1          0   
1             0               14.0                 5.4          0          0   
2             0               11.8                 6.3          1          1   
3             0               14.4                 6.1          0          1   
4             1               13.5                 5.9          0          0   
...         ...                ...                 ...        ...        ...   
4996          1               13.6                 5.1          0          0   
4997          1               11.9                 5.4          0          0   
4998          1               12.9                 5.7          0          0   
4999          1               13.2                 6.2          0          0   
5000          1               15.4                 5.4          1          1   

      lips_thin  distance_nose_to_lip_long  gender  
0             1                          1       0  
1             1                          0       1  
2             1                          1       0  
3             1                          1       0  
4             0                          0       1  
...         ...                        ...     ...  
4996          0                          0       1  
4997          0                          0       1  
4998          0                          0       1  
4999          0                          0       1  
5000          1                          1       0  

[5001 rows x 8 columns]

In [9]:
gender_data.describe()

long_hair  forehead_width_cm  forehead_height_cm    nose_wide  \
count  5001.000000        5001.000000         5001.000000  5001.000000   
mean      0.869626          13.181484            5.946311     0.493901   
std       0.336748           1.107128            0.541268     0.500013   
min       0.000000          11.400000            5.100000     0.000000   
25%       1.000000          12.200000            5.500000     0.000000   
50%       1.000000          13.100000            5.900000     0.000000   
75%       1.000000          14.000000            6.400000     1.000000   
max       1.000000          15.500000            7.100000     1.000000   

         nose_long    lips_thin  distance_nose_to_lip_long      gender  
count  5001.000000  5001.000000                5001.000000  5001.00000  
mean      0.507898     0.493101                   0.498900     0.50010  
std       0.499988     0.500002                   0.500049     0.50005  
min       0.000000     0.000000                   0.000000     0.00000  
25%       0.000000     0.000000                   0.000000     0.00000  
50%       1.000000     0.000000                   0.000000     1.00000  
75%       1.000000     1.000000                   1.000000     1.00000  
max       1.000000     1.000000                   1.000000     1.00000

In [10]:
features=gender_data.iloc[:,:-1]
features

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0             1               11.8                 6.1          1          0   
1             0               14.0                 5.4          0          0   
2             0               11.8                 6.3          1          1   
3             0               14.4                 6.1          0          1   
4             1               13.5                 5.9          0          0   
...         ...                ...                 ...        ...        ...   
4996          1               13.6                 5.1          0          0   
4997          1               11.9                 5.4          0          0   
4998          1               12.9                 5.7          0          0   
4999          1               13.2                 6.2          0          0   
5000          1               15.4                 5.4          1          1   

      lips_thin  distance_nose_to_lip_long  
0             1                          1  
1             1                          0  
2             1                          1  
3             1                          1  
4             0                          0  
...         ...                        ...  
4996          0                          0  
4997          0                          0  
4998          0                          0  
4999          0                          0  
5000          1                          1  

[5001 rows x 7 columns]

In [11]:
gender=gender_data["gender"]
gender

0       0
1       1
2       0
3       0
4       1
       ..
4996    1
4997    1
4998    1
4999    1
5000    0
Name: gender, Length: 5001, dtype: int64

In [12]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm

In [13]:
scaler=StandardScaler()
norm_data=scaler.fit_transform(features)
norm_features=pd.DataFrame(norm_data,columns=features.columns)


In [14]:
norm_features

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0      0.387194          -1.247933            0.283971   1.012273  -1.015924   
1     -2.582682           0.739389           -1.009418  -0.987876  -1.015924   
2     -2.582682          -1.247933            0.653511   1.012273   0.984326   
3     -2.582682           1.100720            0.283971  -0.987876   0.984326   
4      0.387194           0.287725           -0.085568  -0.987876  -1.015924   
...         ...                ...                 ...        ...        ...   
4996   0.387194           0.378057           -1.563727  -0.987876  -1.015924   
4997   0.387194          -1.157600           -1.009418  -0.987876  -1.015924   
4998   0.387194          -0.254272           -0.455108  -0.987876  -1.015924   
4999   0.387194           0.016726            0.468741  -0.987876  -1.015924   
5000   0.387194           2.004048           -1.009418   1.012273   0.984326   

      lips_thin  distance_nose_to_lip_long  
0      1.013894                   1.002202  
1      1.013894                  -0.997803  
2      1.013894                   1.002202  
3      1.013894                   1.002202  
4     -0.986297                  -0.997803  
...         ...                        ...  
4996  -0.986297                  -0.997803  
4997  -0.986297                  -0.997803  
4998  -0.986297                  -0.997803  
4999  -0.986297                  -0.997803  
5000   1.013894                   1.002202  

[5001 rows x 7 columns]

In [15]:
train_ft,test_ft,train_labels,test_labels=train_test_split(norm_features,gender,test_size=0.2, train_size=0.8)

In [16]:
print("----------------Train data------------------------\n")
print(" train data features shape {} \n train data labels shape {}\n".format(train_ft.shape,train_labels.shape))
print("-----------------Test data-------------------------\n")
print(" test data features shape {} \n test data labels shape {}".format(test_ft.shape,test_labels.shape))

----------------Train data------------------------

 train data features shape (4000, 7) 
 train data labels shape (4000,)

-----------------Test data-------------------------

 test data features shape (1001, 7) 
 test data labels shape (1001,)


In [17]:
svm_clf=svm.SVC(kernel="linear")


In [18]:
svm_clf.fit(train_ft,train_labels)

SVC(kernel='linear')

In [19]:
pred_labels=svm_clf.predict(test_ft)

In [20]:
(sum(pred_labels==test_labels)/len(pred_labels))*100

96.8031968031968

In [21]:
from sklearn.metrics import classification_report

In [22]:
print(classification_report(pred_labels,test_labels))

              precision    recall  f1-score   support

           0       0.97      0.96      0.97       502
           1       0.96      0.97      0.97       499

    accuracy                           0.97      1001
   macro avg       0.97      0.97      0.97      1001
weighted avg       0.97      0.97      0.97      1001



The svm fucntion also provides us with classes_ ,n_support_, support_ attributes which specify the attributes of the classifier built. The classes_ gives us the number of classes, n_support gives us the support vectors for each class and the support_ gives the indexes of the support vectors. From the results we see that the there are 149 support vectors for male class and 148 support vectors for female class.

In [23]:
svm_clf.classes_

array([0, 1])

In [24]:
svm_clf.n_support_

array([154, 152], dtype=int32)

In [25]:
svm_clf.support_

array([   5,   12,   44,   96,  108,  109,  124,  187,  190,  234,  274,
        315,  340,  394,  424,  426,  518,  545,  657,  704,  712,  750,
        774,  806,  826,  829,  833,  864,  903,  915,  919,  925,  963,
        976,  998, 1014, 1121, 1137, 1171, 1206, 1210, 1214, 1253, 1263,
       1328, 1332, 1336, 1365, 1369, 1403, 1440, 1456, 1463, 1554, 1577,
       1599, 1602, 1642, 1650, 1662, 1679, 1702, 1712, 1741, 1787, 1820,
       1821, 1875, 1887, 1893, 1930, 1934, 1951, 1961, 1979, 1984, 2039,
       2068, 2075, 2116, 2121, 2130, 2164, 2211, 2283, 2289, 2317, 2357,
       2471, 2492, 2510, 2533, 2559, 2562, 2621, 2637, 2656, 2668, 2678,
       2702, 2726, 2743, 2750, 2751, 2752, 2756, 2760, 2776, 2840, 2864,
       2897, 2903, 2912, 2918, 2934, 2950, 2968, 2980, 3012, 3021, 3022,
       3025, 3040, 3046, 3061, 3075, 3078, 3133, 3151, 3174, 3181, 3267,
       3389, 3423, 3429, 3445, 3481, 3560, 3576, 3587, 3625, 3637, 3718,
       3760, 3762, 3774, 3817, 3828, 3868, 3886, 39

In [26]:
svm_clf.feature_names_in_

array(['long_hair', 'forehead_width_cm', 'forehead_height_cm',
       'nose_wide', 'nose_long', 'lips_thin', 'distance_nose_to_lip_long'],
      dtype=object)

Suppose we have a student who has short hair, 11 cm width of forehead, 6 cm height of forehead,nose is not wide, nose is long, lips are thin, the distance between the nose and the lip is long. The the feature vectors is as follows:
a.	Long_hair = 0 

b.	Forehead_width_cm=11

c.	Forehead_height_cm=6

d.	Nose_wide=0

e.	Nose long=1

f.	Lips thin=1


Before we apply the predict fucntion we need to scale the attributes using a standard scaler. Form the results we see that the svm classifier output is 0, which means that the student is a male student. 

In [27]:
norm_ft=scaler.fit_transform([[0,11,6,0,1,1,1]])
svm_clf.predict(norm_ft)

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([0])